"""
Generates the injury HUD icons for the Liminalis resource pack.

Every icon is hand-drawn as an ASCII grid below rather than composed from
primitives. That is deliberate: 16x16 symbolic icons live or die on their
silhouette, and shapes assembled from circles and polygons at this size come
out as mush. Drawing them as text means each pixel was chosen.

The palette matters as much as the shape. Ordinary injuries are warm and
readable; mortal wounds are darker, desaturated, and outlined in dried blood
so they are distinguishable from ordinary ones at a glance without reading
anything - which is the whole point of a HUD you are meant to ignore until
it matters.

Run:  python tools/build_icons.py
"""

import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "pack" / "assets" / "liminalis" / "textures" / "font" / "injury"
FONT = ROOT / "pack" / "assets" / "liminalis" / "font" / "hud.json"

# Codepoint order. The font file and the plugin's glyph map are both generated or checked
# against this list, so the three can never drift apart - which used to be the easiest way
# to ship a HUD that shows players empty boxes.
CODEPOINTS = [
    ("bleeding", 0xE001),
    ("sprained_ankle", 0xE002),
    ("burns", 0xE003),
    ("concussion", 0xE004),
    ("punctured_lung", 0xE005),
    ("lost_arm", 0xE006),
    ("broken_legs", 0xE007),
    ("charred", 0xE008),
    ("presence", 0xE009),
    ("frostbite", 0xE00A),
    ("poisoned_blood", 0xE00B),
    ("shock", 0xE00C),
    ("impaled", 0xE00D),
    ("frozen_marrow", 0xE00E),
    ("rotting_wound", 0xE00F),
    ("failing_body", 0xE010),
]

# Shared palette. Keys are the characters used in the grids.
#   .  transparent      o  outline
#   #  body             +  highlight
#   x  accent
TRANSPARENT = (0, 0, 0, 0)


def palette(outline, body, highlight, accent):
    return {
        ".": TRANSPARENT,
        "o": outline,
        "#": body,
        "+": highlight,
        "x": accent,
    }


# --------------------------------------------------------------------------
# Ordinary injuries - warm, legible, clearly temporary
# --------------------------------------------------------------------------

BLEEDING = """
................
.......oo.......
.......oo.......
......o##o......
......o##o......
.....o####o.....
.....o####o.....
....o######o....
....o##++##o....
...o###++###o...
...o########o...
...o########o...
....o######o....
.....o####o.....
......oooo......
................
"""

SPRAINED_ANKLE = """
................
.....oooo.......
....o####o......
....o#++#o......
....o####o......
....o####o......
....o####o......
...oxxxxxxo.....
...ox++++xo.....
...oxxxxxxo.....
....o####o......
....o#####o.....
....o######o....
....o#######o...
.....ooooooo....
................
"""

BURNS = """
................
........o.......
.......o#o......
.......o#o......
......o##o......
......o#+o......
.....o##+#o.....
.....o#++#o.....
....o##++##o....
....o#+xx+#o....
...o##+xx+##o...
...o#++xx++#o...
...o##+xx+##o...
....o##++##o....
.....oooooo.....
................
"""

CONCUSSION = """
................
...o..o..o..o...
....o.o..o.o....
.....ooooo......
....o#####o.....
...o##+++##o....
..o##+xxx+##o...
..o#+x###x+#o...
..o#+x###x+#o...
..o##+xxx+##o...
...o##+++##o....
....o#####o.....
.....ooooo......
....o.o..o.o....
...o..o..o..o...
................
"""

PUNCTURED_LUNG = """
................
.......oo.......
.......##.......
......o##o......
.....o####o.....
....o##++##o....
...o##+xx+##o...
...o#+xoox+#o...
...o#+xoox+#o...
...o##+xx+##o...
...o########o...
...o###..###o...
....o##..##o....
.....o####o.....
......oooo......
................
"""

# --------------------------------------------------------------------------
# Mortal wounds - darker, desaturated, dried-blood outline
# --------------------------------------------------------------------------

LOST_ARM = """
................
.....oooo.......
....o####o......
....o#++#o......
....o####o......
....o####o......
....o####o......
....o####o......
....o####o......
....o####o......
...oxxxxxxo.....
..ox#xx#x#xo....
..oxx#xx#xxo....
...oxxxxxxo.....
....oooooo......
................
"""

BROKEN_LEGS = """
................
..oo........oo..
.o##o......o##o.
.o#+#o....o#+#o.
.o####o..o####o.
..o####oo####o..
...o##x..x##o...
....o#x..x#o....
....o#x..x#o....
...o##x..x##o...
..o####oo####o..
.o####o..o####o.
.o#+#o....o#+#o.
.o##o......o##o.
..oo........oo..
................
"""

CHARRED = """
................
........o.......
.......o#o......
.......o#o......
......o##o......
......o#xo......
.....o##x#o.....
.....o#xx#o.....
....o##xx##o....
....o#xoox#o....
...o##xoox##o...
...o#xxooxx#o...
...o##xoox##o...
....o##xx##o....
.....oooooo.....
................
"""

PRESENCE = """
................
.......oo.......
......o##o......
.....o#++#o.....
....o#+xx+#o....
...o#+xoox+#o...
..o#+xo..ox+#o..
..o#xo....ox#o..
..o#xo....ox#o..
..o#+xo..ox+#o..
...o#+xoox+#o...
....o#+xx+#o....
.....o#++#o.....
......o##o......
.......oo.......
................
"""


# --------------------------------------------------------------------------
# Added with the damage-category audit: frost, withering and the catch-all all
# gained wounds, and piercing finally got the mortal one it never had.
# --------------------------------------------------------------------------

FROSTBITE = """
................
......o..o......
.....o#o.o#o....
.....o#+oo+#o...
......o+##+o....
.....o##++##o...
....o#+xxxx+#o..
...o#+xx##xx+#o.
...o#+xx##xx+#o.
....o#+xxxx+#o..
.....o##++##o...
......o+##+o....
.....o#+oo+#o...
.....o#o.o#o....
......o..o......
................
"""

POISONED_BLOOD = """
................
.......oo.......
.......##.......
......o##o......
......o##o......
.....o####o.....
.....o#++#o.....
....o##oo##o....
....o#o..o#o....
...o##o..o##o...
...o#+xoox+#o...
...o##+xx+##o...
....o##++##o....
.....o####o.....
......oooo......
................
"""

SHOCK = """
................
....oooooooo....
...o########o...
..o##oooooo##o..
..o#o......o#o..
..o#o.oooo.o#o..
..o#o.o##o.o#o..
..o#o.o#+o.o#o..
..o#o.o##o.o#o..
..o#o.oooo.o#o..
..o#o......o#o..
..o##oooooo##o..
...o########o...
....oooooooo....
................
................
"""

IMPALED = """
................
.......oo.......
......o##o......
.....o#++#o.....
.....o####o.....
oooooo####oooooo
o++xxx####xxx++o
oooooo####oooooo
.....o####o.....
.....o#++#o.....
....o##++##o....
....o######o....
....o##..##o....
.....o#..#o.....
.....oo..oo.....
................
"""

FROZEN_MARROW = """
................
..oo........oo..
.o##o......o##o.
.o#+#o....o#+#o.
.o####oooo####o.
..o##xxxxxx##o..
...o#xxxxxx#o...
...o#x+..+x#o...
...o#x+..+x#o...
...o#xxxxxx#o...
..o##xxxxxx##o..
.o####oooo####o.
.o#+#o....o#+#o.
.o##o......o##o.
..oo........oo..
................
"""

ROTTING_WOUND = """
................
.....o..oo......
....oo.o##o.....
...o##oo##xo....
..o##xxxx##oo...
.o##xx####xx##o.
.o#xx##++##xx#o.
.o#x##+xx+##x#o.
.o#x##+xx+##x#o.
.o#xx##++##xx#o.
.o##xx####xx##o.
..o##xxxx##oo...
...o##oo##xo....
....oo.o##o.....
.....o..oo......
................
"""

FAILING_BODY = """
................
..oooo....oooo..
.o####o..o####o.
o##++##oo##++##o
o#++###ox#++###o
o######ox######o
.o#####xox#####o
..o####x.x####o.
...o###xox###o..
....o##x.x##o...
.....o#xox#o....
......o#x#o.....
.......oxo......
........o.......
................
................
"""


ICONS = {

    "bleeding": (BLEEDING, palette((60, 8, 8, 255), (168, 26, 26, 255),
                                   (214, 66, 66, 255), (120, 16, 16, 255))),
    "sprained_ankle": (SPRAINED_ANKLE, palette((70, 44, 12, 255), (196, 140, 56, 255),
                                               (232, 186, 110, 255), (238, 232, 214, 255))),
    "burns": (BURNS, palette((66, 24, 6, 255), (214, 96, 20, 255),
                             (240, 168, 56, 255), (250, 226, 130, 255))),
    "concussion": (CONCUSSION, palette((70, 58, 12, 255), (206, 186, 62, 255),
                                       (238, 226, 132, 255), (140, 118, 30, 255))),
    "punctured_lung": (PUNCTURED_LUNG, palette((34, 52, 66, 255), (110, 152, 184, 255),
                                               (166, 202, 228, 255), (62, 92, 118, 255))),
    # Mortal: outline is dried blood, bodies are desaturated
    "lost_arm": (LOST_ARM, palette((72, 10, 10, 255), (140, 116, 108, 255),
                                   (178, 156, 148, 255), (146, 24, 24, 255))),
    "broken_legs": (BROKEN_LEGS, palette((72, 10, 10, 255), (206, 200, 184, 255),
                                         (236, 232, 220, 255), (110, 96, 88, 255))),
    "charred": (CHARRED, palette((72, 10, 10, 255), (62, 58, 56, 255),
                                 (104, 98, 94, 255), (28, 26, 24, 255))),
    "frostbite": (FROSTBITE, palette((28, 50, 72, 255), (140, 190, 220, 255),
                                     (215, 240, 252, 255), (86, 146, 186, 255))),
    "poisoned_blood": (POISONED_BLOOD, palette((24, 54, 26, 255), (96, 164, 74, 255),
                                               (170, 214, 120, 255), (58, 110, 48, 255))),
    "shock": (SHOCK, palette((44, 54, 60, 255), (150, 168, 178, 255),
                             (208, 222, 230, 255), (96, 118, 130, 255))),
    # Mortal: same dried-blood outline as the others, so severity reads before subject does.
    "impaled": (IMPALED, palette((72, 10, 10, 255), (150, 132, 124, 255),
                                 (188, 172, 164, 255), (146, 24, 24, 255))),
    "frozen_marrow": (FROZEN_MARROW, palette((72, 10, 10, 255), (198, 206, 214, 255),
                                             (232, 240, 248, 255), (120, 168, 198, 255))),
    "rotting_wound": (ROTTING_WOUND, palette((72, 10, 10, 255), (96, 88, 62, 255),
                                             (140, 132, 88, 255), (74, 92, 52, 255))),
    "failing_body": (FAILING_BODY, palette((72, 10, 10, 255), (128, 74, 74, 255),
                                           (168, 104, 104, 255), (60, 50, 50, 255))),
    # Not an injury: the mark shown when something the Singularity sent is nearby.
    # Cold violet-grey, so it never reads as a wound among the wound icons.
    "presence": (PRESENCE, palette((38, 32, 52, 255), (128, 118, 160, 255),
                                   (176, 168, 206, 255), (74, 66, 100, 255))),
}


def render(name, grid, colours):
    """
    Turns one ASCII grid into a 16x16 icon, refusing anything that is not exactly that.

    The size check is not paranoia. This used to slice the grid to 16x16 and pad the rest
    with transparency, so a row one character short - which is trivially easy when you are
    hand-drawing sixteen of these - produced an icon with a bite out of one edge and no
    complaint from anywhere. At sixteen pixels that reads as a slightly odd drawing rather
    than as a bug, which is exactly how it would survive all the way to a player's screen.
    """
    size = 16
    rows = grid.strip().split("\n")

    if len(rows) != size:
        raise ValueError("%s: grid is %d rows, must be %d" % (name, len(rows), size))
    for y, row in enumerate(rows):
        if len(row) != size:
            raise ValueError("%s: row %d is %d characters, must be %d\n  %r"
                             % (name, y, len(row), size, row))
        unknown = sorted(set(row) - set(colours))
        if unknown:
            raise ValueError("%s: row %d uses unknown characters %s" % (name, y, unknown))

    image = Image.new("RGBA", (size, size), TRANSPARENT)
    pixels = image.load()
    for y, row in enumerate(rows):
        for x, char in enumerate(row):
            pixels[x, y] = colours[char]
    return image


def build_pack_icon(path):
    """
    The pack icon: the pale garden reduced to 128 pixels.

    A vertical grey gradient with a single darker band across it - the horizon
    of a place with nothing on it.
    """
    size = 128
    image = Image.new("RGBA", (size, size), (0, 0, 0, 255))
    pixels = image.load()

    for y in range(size):
        # Pale at the top, sinking to near-black at the bottom.
        t = y / (size - 1)
        value = int(176 - (t ** 1.4) * 150)
        for x in range(size):
            # A faint horizontal band two thirds down, like a treeline with no trees.
            band = 18 if 82 <= y <= 86 else 0
            shade = max(0, value - band)
            pixels[x, y] = (shade, shade + 4, shade + 6, 255)

    image.save(path)


def build_font():
    """
    Writes hud.json from CODEPOINTS.

    Generated rather than hand-maintained because a font file that disagrees with the
    textures beside it produces empty boxes on players' screens and no error anywhere.
    """
    providers = [
        {
            "type": "bitmap",
            "file": f"liminalis:font/injury/{name}.png",
            "ascent": 8,
            "height": 10,
            "chars": [chr(cp)],
        }
        for name, cp in CODEPOINTS
    ]
    FONT.parent.mkdir(parents=True, exist_ok=True)
    # Line endings are pinned to LF rather than left to the platform default. Python
    # translates a newline to CRLF on Windows, git normalises the committed file back to LF,
    # and the pack zip hashes whichever bytes are on disk - so without this the sha1 depends
    # on whether you last ran this script or last cloned the repo, and two people building
    # the same commit get two different hashes for identical content.
    FONT.write_text(json.dumps({"providers": providers}, indent=2, ensure_ascii=True) + chr(10),
                    encoding="utf-8", newline=chr(10))


def check_coverage():
    """Every codepoint needs a texture, and every texture needs a codepoint."""
    named = {name for name, _ in CODEPOINTS}
    drawn = set(ICONS)
    missing_art = named - drawn
    missing_codepoint = drawn - named
    if missing_art:
        raise SystemExit(f"codepoints with no icon defined: {sorted(missing_art)}")
    if missing_codepoint:
        raise SystemExit(f"icons with no codepoint: {sorted(missing_codepoint)}")


def main():
    check_coverage()
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (grid, colours) in ICONS.items():
        target = OUT / f"{name}.png"
        render(name, grid, colours).save(target)
        print(f"  {target.relative_to(ROOT)}")

    icon = ROOT / "pack" / "pack.png"
    build_pack_icon(icon)
    print(f"  {icon.relative_to(ROOT)}")

    build_font()
    print(f"  {FONT.relative_to(ROOT)}")
    print(f"{len(ICONS)} icons + pack icon + font written")


if __name__ == "__main__":
    main()
