"""
Generates the injury HUD icons for the Liminalis resource pack.

Every icon is hand-drawn as an ASCII grid below rather than composed from
primitives. That is deliberate: 16x16 symbolic icons live or die on their
silhouette, and shapes assembled from circles and polygons at this size come
out as mush. Drawing them as text means each pixel was chosen.

The palette matters as much as the shape. Ordinary injuries are warm and
readable; mortal wounds are darker, desaturated, and outlined in dried blood
so they are distinguishable from ordinary ones at a glance without reading
anything - which is the whole point of a HUD you are meant to ignore until
it matters.

Run:  python tools/build_icons.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "pack" / "assets" / "liminalis" / "textures" / "font" / "injury"

# Shared palette. Keys are the characters used in the grids.
#   .  transparent      o  outline
#   #  body             +  highlight
#   x  accent
TRANSPARENT = (0, 0, 0, 0)


def palette(outline, body, highlight, accent):
    return {
        ".": TRANSPARENT,
        "o": outline,
        "#": body,
        "+": highlight,
        "x": accent,
    }


# --------------------------------------------------------------------------
# Ordinary injuries - warm, legible, clearly temporary
# --------------------------------------------------------------------------

BLEEDING = """
................
.......oo.......
.......oo.......
......o##o......
......o##o......
.....o####o.....
.....o####o.....
....o######o....
....o##++##o....
...o###++###o...
...o########o...
...o########o...
....o######o....
.....o####o.....
......oooo......
................
"""

SPRAINED_ANKLE = """
................
.....oooo.......
....o####o......
....o#++#o......
....o####o......
....o####o......
....o####o......
...oxxxxxxo.....
...ox++++xo.....
...oxxxxxxo.....
....o####o......
....o#####o.....
....o######o....
....o#######o...
.....ooooooo....
................
"""

BURNS = """
................
........o.......
.......o#o......
.......o#o......
......o##o......
......o#+o......
.....o##+#o.....
.....o#++#o.....
....o##++##o....
....o#+xx+#o....
...o##+xx+##o...
...o#++xx++#o...
...o##+xx+##o...
....o##++##o....
.....oooooo.....
................
"""

CONCUSSION = """
................
...o..o..o..o...
....o.o..o.o....
.....ooooo......
....o#####o.....
...o##+++##o....
..o##+xxx+##o...
..o#+x###x+#o...
..o#+x###x+#o...
..o##+xxx+##o...
...o##+++##o....
....o#####o.....
.....ooooo......
....o.o..o.o....
...o..o..o..o...
................
"""

PUNCTURED_LUNG = """
................
.......oo.......
.......##.......
......o##o......
.....o####o.....
....o##++##o....
...o##+xx+##o...
...o#+xoox+#o...
...o#+xoox+#o...
...o##+xx+##o...
...o########o...
...o###..###o...
....o##..##o....
.....o####o.....
......oooo......
................
"""

# --------------------------------------------------------------------------
# Mortal wounds - darker, desaturated, dried-blood outline
# --------------------------------------------------------------------------

LOST_ARM = """
................
.....oooo.......
....o####o......
....o#++#o......
....o####o......
....o####o......
....o####o......
....o####o......
....o####o......
....o####o......
...oxxxxxxo.....
..ox#xx#x#xo....
..oxx#xx#xxo....
...oxxxxxxo.....
....oooooo......
................
"""

BROKEN_LEGS = """
................
..oo........oo..
.o##o......o##o.
.o#+#o....o#+#o.
.o####o..o####o.
..o####oo####o..
...o##x..x##o...
....o#x..x#o....
....o#x..x#o....
...o##x..x##o...
..o####oo####o..
.o####o..o####o.
.o#+#o....o#+#o.
.o##o......o##o.
..oo........oo..
................
"""

CHARRED = """
................
........o.......
.......o#o......
.......o#o......
......o##o......
......o#xo......
.....o##x#o.....
.....o#xx#o.....
....o##xx##o....
....o#xoox#o....
...o##xoox##o...
...o#xxoox x o..
...o##xoox##o...
....o##xx##o....
.....oooooo.....
................
"""

ICONS = {
    "bleeding": (BLEEDING, palette((60, 8, 8, 255), (168, 26, 26, 255),
                                   (214, 66, 66, 255), (120, 16, 16, 255))),
    "sprained_ankle": (SPRAINED_ANKLE, palette((70, 44, 12, 255), (196, 140, 56, 255),
                                               (232, 186, 110, 255), (238, 232, 214, 255))),
    "burns": (BURNS, palette((66, 24, 6, 255), (214, 96, 20, 255),
                             (240, 168, 56, 255), (250, 226, 130, 255))),
    "concussion": (CONCUSSION, palette((70, 58, 12, 255), (206, 186, 62, 255),
                                       (238, 226, 132, 255), (140, 118, 30, 255))),
    "punctured_lung": (PUNCTURED_LUNG, palette((34, 52, 66, 255), (110, 152, 184, 255),
                                               (166, 202, 228, 255), (62, 92, 118, 255))),
    # Mortal: outline is dried blood, bodies are desaturated
    "lost_arm": (LOST_ARM, palette((72, 10, 10, 255), (140, 116, 108, 255),
                                   (178, 156, 148, 255), (146, 24, 24, 255))),
    "broken_legs": (BROKEN_LEGS, palette((72, 10, 10, 255), (206, 200, 184, 255),
                                         (236, 232, 220, 255), (110, 96, 88, 255))),
    "charred": (CHARRED, palette((72, 10, 10, 255), (62, 58, 56, 255),
                                 (104, 98, 94, 255), (28, 26, 24, 255))),
}


def render(grid, colours):
    rows = [row for row in grid.strip("\n").split("\n")]
    size = 16
    image = Image.new("RGBA", (size, size), TRANSPARENT)
    pixels = image.load()

    for y, row in enumerate(rows[:size]):
        for x, char in enumerate(row[:size]):
            pixels[x, y] = colours.get(char, TRANSPARENT)
    return image


def build_pack_icon(path):
    """
    The pack icon: the pale garden reduced to 128 pixels.

    A vertical grey gradient with a single darker band across it - the horizon
    of a place with nothing on it.
    """
    size = 128
    image = Image.new("RGBA", (size, size), (0, 0, 0, 255))
    pixels = image.load()

    for y in range(size):
        # Pale at the top, sinking to near-black at the bottom.
        t = y / (size - 1)
        value = int(176 - (t ** 1.4) * 150)
        for x in range(size):
            # A faint horizontal band two thirds down, like a treeline with no trees.
            band = 18 if 82 <= y <= 86 else 0
            shade = max(0, value - band)
            pixels[x, y] = (shade, shade + 4, shade + 6, 255)

    image.save(path)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (grid, colours) in ICONS.items():
        target = OUT / f"{name}.png"
        render(grid, colours).save(target)
        print(f"  {target.relative_to(ROOT)}")

    icon = ROOT / "pack" / "pack.png"
    build_pack_icon(icon)
    print(f"  {icon.relative_to(ROOT)}")
    print(f"{len(ICONS)} icons + pack icon written")


if __name__ == "__main__":
    main()
